# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Driftr < Formula
  desc "Fast JavaScript toolchain versioning without the friction"
  homepage "https://github.com/DriftrLabs/driftr"
  version "0.11.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DriftrLabs/Driftr/releases/download/v0.11.2/driftr_0.11.2_darwin_amd64.tar.gz"
      sha256 "fa2f2bd145c2cb197d12bab354b84a6b975e2ad792b7004bca27121126e1becb"

      define_method(:install) do
        bin.install "driftr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DriftrLabs/Driftr/releases/download/v0.11.2/driftr_0.11.2_darwin_arm64.tar.gz"
      sha256 "d2c3eae4b850eea64bf9a86bdec28f899cc40c1b69691e2f382b2694025449dc"

      define_method(:install) do
        bin.install "driftr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftrLabs/Driftr/releases/download/v0.11.2/driftr_0.11.2_linux_amd64.tar.gz"
      sha256 "c63751e7e0882471c31cf9dd808dc0bbad9746a1f5a0ee66d81aee181454f7a9"
      define_method(:install) do
        bin.install "driftr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftrLabs/Driftr/releases/download/v0.11.2/driftr_0.11.2_linux_arm64.tar.gz"
      sha256 "e8f566fc5af62206de2fc4c3e9ee663527f0c092ab3ae2f076740e5f7148d45d"
      define_method(:install) do
        bin.install "driftr"
      end
    end
  end

  def caveats
    <<~EOS
      Run setup to create shims and data directories:
        driftr setup

      Add ~/.driftr/bin to the FRONT of your PATH (before Homebrew):
        echo 'export PATH="$HOME/.driftr/bin:$PATH"' >> ~/.zshenv
        echo 'export PATH="$HOME/.driftr/bin:$PATH"' >> ~/.zshrc

      Or run `driftr doctor --fix` to configure PATH automatically.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/driftr --version")
  end
end
