# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Driftr < Formula
  desc "Fast JavaScript toolchain versioning without the friction"
  homepage "https://github.com/DriftrLabs/driftr"
  version "0.11.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DriftrLabs/Driftr/releases/download/v0.11.3/driftr_0.11.3_darwin_amd64.tar.gz"
      sha256 "32b751218a75065465c12b32b97f1c89906e2929c626ddca6361169e3400ae48"

      define_method(:install) do
        bin.install "driftr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DriftrLabs/Driftr/releases/download/v0.11.3/driftr_0.11.3_darwin_arm64.tar.gz"
      sha256 "1cad73270bed2f2651df2972430fb9d117cbe9d9d181319bb98e961a8dddde3a"

      define_method(:install) do
        bin.install "driftr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftrLabs/Driftr/releases/download/v0.11.3/driftr_0.11.3_linux_amd64.tar.gz"
      sha256 "9f0561401c27757222e76e46fdf6e2f13064ce9c6acbce4c484c44f309d120d6"
      define_method(:install) do
        bin.install "driftr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftrLabs/Driftr/releases/download/v0.11.3/driftr_0.11.3_linux_arm64.tar.gz"
      sha256 "42f648c3cc3c75da14acf677f67bc0f2710dfff9b73fddf79d38f2931a0342da"
      define_method(:install) do
        bin.install "driftr"
      end
    end
  end

  def caveats
    <<~EOS
      Run setup to create shims and data directories:
        driftr setup

      Add ~/.driftr/bin to the FRONT of your PATH (before Homebrew):
        echo 'export PATH="$HOME/.driftr/bin:$PATH"' >> ~/.zshenv
        echo 'export PATH="$HOME/.driftr/bin:$PATH"' >> ~/.zshrc

      Or run `driftr doctor --fix` to configure PATH automatically.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/driftr --version")
  end
end
