# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Driftr < Formula
  desc "Fast JavaScript toolchain versioning without the friction"
  homepage "https://github.com/DriftrLabs/driftr"
  version "0.10.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DriftrLabs/Driftr/releases/download/v0.10.2/driftr_0.10.2_darwin_amd64.tar.gz"
      sha256 "16bd7dc4d94a7980b94ad1b1faaf69dda4729b13bb5b2c9e3a7e03a4207f73e2"

      define_method(:install) do
        bin.install "driftr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DriftrLabs/Driftr/releases/download/v0.10.2/driftr_0.10.2_darwin_arm64.tar.gz"
      sha256 "085e8cca39050945028f69e4245aabc338bd73c9349d497ec97b501f4fd925b6"

      define_method(:install) do
        bin.install "driftr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftrLabs/Driftr/releases/download/v0.10.2/driftr_0.10.2_linux_amd64.tar.gz"
      sha256 "1efab9b548c4ccfced7b89c39267fcec19287112cea9e67e0541c8a2eb23f863"
      define_method(:install) do
        bin.install "driftr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftrLabs/Driftr/releases/download/v0.10.2/driftr_0.10.2_linux_arm64.tar.gz"
      sha256 "14087d672064bf350977534566790d67c8e9e66999803cf4b301cb23c555a919"
      define_method(:install) do
        bin.install "driftr"
      end
    end
  end

  def caveats
    <<~EOS
      Run setup to create shims and data directories:
        driftr setup

      Add ~/.driftr/bin to the FRONT of your PATH (before Homebrew):
        echo 'export PATH="$HOME/.driftr/bin:$PATH"' >> ~/.zshenv
        echo 'export PATH="$HOME/.driftr/bin:$PATH"' >> ~/.zshrc

      Or run `driftr doctor --fix` to configure PATH automatically.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/driftr --version")
  end
end
